export const Questions = [
    {
      prompt: "What is the purpose of a for loop in programming?",
      optionA: "To perform repetitive tasks",
      optionB: " To declare variables",
      optionC: "To handle exceptions",
      optionD: " To define classes",
      answer: "optionA",
    },
    {
      prompt: "What does HTML stand for?",
      optionA: "HyperText Markup Language",
      optionB: " High-Level Programming Language",
      optionC: "Home Tool Management Library",
      optionD: "Human-Text Manipulation Logic",
      answer: "optionA",
    },
    {
      prompt: "Which of this is not a javascript framework?",
      optionA: "React",
      optionB: "Angular",
      optionC: "Vue",
      optionD: "Java",
      answer: "optionD",
    },
    {
      prompt: "What is the difference between == and === in JavaScript?",
      optionA: "There is no difference, they are the same.",
      optionB: "== compares values, === compares both values and types.",
      optionC: "=== compares values, == compares both values and types.",
      optionD: "== is used for assignment, === is used for comparison.",
      answer: "optionB",
    },
    {
      prompt: "What is the main difference between a function and a method in programming?",
      optionA: "Functions can be called from any class, methods are specific to a class.",
      optionB: "Functions are defined inside classes, methods are standalone.",
      optionC: "Functions are used for calculations, methods are used for manipulation.",
      optionD: "There is no difference, the terms can be used interchangeably.",
      answer: "optionD",
    },
    {
      prompt: "What does CSS stand for?",
      optionA: " Cascading Style Sheets",
      optionB: " Computer System Security",
      optionC: " Cross-Site Scripting",
      optionD: "Centralized Source Storage",
      answer: "optionA",
    },
    {
      prompt: "What does the acronym API stand for?",
      optionA: "Application Program Interface",
      optionB: "Automated Programming Interface",
      optionC: "Advanced Programming Instructions",
      optionD: "Algorithmic Protocol Integration",
      answer: "optionA",
    },
    {
      prompt: "What is the purpose of version control systems like Git?",
      optionA: "To compile and run code",
      optionB: "To write and test unit tests",
      optionC: "To optimize code performance",
      optionD: "To manage and track changes to code over time",
      answer: "optionD",
    },
    {
      prompt: "In Python, how do you declare a variable?",
      optionA: "var x = 5",
      optionB: "int x = 5",
      optionC: "set x = 5",
      optionD: "x = 5",
      answer: "optionD",
    },
    {
      prompt: "What is the purpose of a constructor in object-oriented programming?",
      optionA: "To define a new class",
      optionB: "To create a new object of a class",
      optionC: "To declare variables within a class",
      optionD: "To implement inheritance between classes",
      answer: "optionB",
    },
    
  ];